default:
    watchexec -c -r "pushd interrato.dev && tailwindcss -m -i input.css -o static/build.css && popd && go run ."

@protect-note slug:
    # Generates a proxy HTML file to expose CSS classes to Tailwind
    grep 'class=' ./interrato.dev/templates/notes/{{slug}}.html | perl -pe 's|^.*?<|<|' | perl -pe 's|(class=".*?").*|\1>|' > ./interrato.dev/templates/notes/{{slug}}_proxy.html
    # Encrypts the selected note with a passphrase chosen interactively using age
    go run ./cmd/age-encrypt/age-encrypt.go ./interrato.dev/templates/notes/{{slug}}.html > ./interrato.dev/templates/notes/{{slug}}.html.age
