all: UTF8_encoding UTF8_decoding

UTF8_encoding: UTF8_encoding.c
	gcc -o UTF8_encoding -Wall -pedantic -O2 UTF8_encoding.c

UTF8_decoding: UTF8_decoding.c
	gcc -o UTF8_decoding -Wall -pedantic -O2 UTF8_decoding.c

clean:
	rm ./UTF8_encoding
	rm ./UTF8_decoding
